In [1]:
import pandas as pd
import numpy as np

In [2]:
link = "https://en.wikipedia.org/wiki/Federative_units_of_Brazil"

states = pd.read_html(link,header=0)[1]

In [3]:
states.columns = map(str.lower, states.columns)
states.head()

,flag and name,code,capital,largest city,area(km2)[1],population(2019)[2],"density (perkm2, 2019)","gdp (r$millions, 2016)[3]",hdi(2017)[4]
0,Acre,AC,Rio Branco,Rio Branco,164124,881935,5.37,13751,0.719
1,Alagoas,AL,Maceió,Maceió,27843,3337357,119.86,49456,0.683
2,Amapá,AP,Macapá,Macapá,142471,845731,5.94,14339,0.740
3,Amazonas,AM,Manaus,Manaus,1559168,4144597,2.66,89017,0.733
4,Bahia,BA,Salvador,Salvador,564723,14873064,26.34,258649,0.714

In [4]:
columns_rename_map = {'flag and name' : 'name', 
                      'area(km2)[1]' : 'area_km2', 
                      'population(2019)[2]' : 'population',
                      'density (perkm2, 2019)' : 'density_perkm2',
                      'gdp (r$millions, 2016)[3]' : 'gdp_r$million',
                      'hdi(2017)[4]' : 'hdi'}
states.rename(columns=columns_rename_map, inplace=True)

In [6]:
states.head()

,name,code,capital,largest city,area_km2,population,density_perkm2,gdp_r$million,hdi
0,Acre,AC,Rio Branco,Rio Branco,164124,881935,5.37,13751,0.719
1,Alagoas,AL,Maceió,Maceió,27843,3337357,119.86,49456,0.683
2,Amapá,AP,Macapá,Macapá,142471,845731,5.94,14339,0.740
3,Amazonas,AM,Manaus,Manaus,1559168,4144597,2.66,89017,0.733
4,Bahia,BA,Salvador,Salvador,564723,14873064,26.34,258649,0.714

In [8]:
states.to_csv('data/states.csv', index=False)